[book]
authors = ["Divyanshu Shulkla"]
language = "en"
multilingual = false
src = "src"
title = "Serverless Siege: AWS Lambda Pentesting Workshop By Securitydojo"
description = "AWS Lambda Pentesting Workshop"
